# Copyright (c) 2014, 2015, Oracle and/or its affiliates. All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA

# binaries
usr/bin/myisamchk
usr/bin/myisamlog
usr/bin/myisampack
usr/bin/my_print_defaults
usr/bin/myblockchain_install_db
usr/bin/myblockchain_secure_installation
usr/bin/myblockchain_ssl_rsa_setup
usr/bin/myblockchain_tzinfo_to_sql
usr/bin/myblockchain_upgrade
usr/bin/myblockchainbinlog
usr/bin/myblockchaind_multi
usr/bin/myblockchaind_safe
usr/bin/perror
usr/bin/replace
usr/bin/resolveip
usr/bin/resolve_stack_dump
usr/sbin/myblockchaind
# debug binary
usr/sbin/myblockchaind-debug
# man pages
usr/share/man/man1/comp_err.1
usr/share/man/man1/myisamchk.1
usr/share/man/man1/myisamlog.1
usr/share/man/man1/myisampack.1
usr/share/man/man1/my_print_defaults.1
usr/share/man/man1/myblockchain_install_db.1
usr/share/man/man1/myblockchain_secure_installation.1
usr/share/man/man1/myblockchain_ssl_rsa_setup.1
usr/share/man/man1/myblockchain_tzinfo_to_sql.1
usr/share/man/man1/myblockchain_upgrade.1
usr/share/man/man1/myblockchainbinlog.1
usr/share/man/man1/myblockchaind_multi.1
usr/share/man/man1/myblockchaind_safe.1
usr/share/man/man1/myblockchain.server.1
usr/share/man/man1/myblockchain-stress-test.pl.1
usr/share/man/man1/perror.1
usr/share/man/man1/replace.1
usr/share/man/man1/resolveip.1
usr/share/man/man1/resolve_stack_dump.1
usr/share/man/man8/myblockchaind.8
# SQL files
usr/share/myblockchain/*.sql
# plugins
usr/lib/myblockchain/plugin/adt_null.so
usr/lib/myblockchain/plugin/auth_socket.so
usr/lib/myblockchain/plugin/innodb_engine.so
usr/lib/myblockchain/plugin/libmemcached.so
usr/lib/myblockchain/plugin/libpluginmecab.so
usr/lib/myblockchain/plugin/locking_service.so
usr/lib/myblockchain/plugin/mypluglib.so
usr/lib/myblockchain/plugin/myblockchain_no_login.so
usr/lib/myblockchain/plugin/rewriter.so
usr/lib/myblockchain/plugin/semisync_master.so
usr/lib/myblockchain/plugin/semisync_slave.so
usr/lib/myblockchain/plugin/validate_password.so
usr/lib/myblockchain/plugin/version_token.so
usr/lib/myblockchain/plugin/debug/adt_null.so
usr/lib/myblockchain/plugin/debug/auth_socket.so
usr/lib/myblockchain/plugin/debug/innodb_engine.so
usr/lib/myblockchain/plugin/debug/libmemcached.so
usr/lib/myblockchain/plugin/debug/libpluginmecab.so
usr/lib/myblockchain/plugin/debug/locking_service.so
usr/lib/myblockchain/plugin/debug/mypluglib.so
usr/lib/myblockchain/plugin/debug/myblockchain_no_login.so
usr/lib/myblockchain/plugin/debug/rewriter.so
usr/lib/myblockchain/plugin/debug/semisync_master.so
usr/lib/myblockchain/plugin/debug/semisync_slave.so
usr/lib/myblockchain/plugin/debug/validate_password.so
usr/lib/myblockchain/plugin/debug/version_token.so
# support files
usr/share/myblockchain/dictionary.txt
usr/share/myblockchain/magic
usr/share/myblockchain/my-default.cnf
usr/share/myblockchain/myblockchain-log-rotate
usr/share/myblockchain/myblockchain-systemd-start
usr/share/myblockchain/myblockchaind_multi.server
# legal
usr/share/doc/myblockchain-community-server/COPYING
usr/share/doc/myblockchain-community-server/README
