import os
import string

srcdir = 'Adapter/impl'
blddir = 'Adapter/impl/build'
VERSION = '0.35'

def set_options(opt):
  opt.tool_options('compiler_cxx')
  opt.add_option('--myblockchain', action='store')

def configure(conf):
  import Options
  
  if(Options.options.myblockchain):
    myblockchain_path = Options.options.myblockchain
  else:
    infile = open('./config.waf', 'r')
    myblockchain_path = infile.read()
 
  myblockchain_path = string.rstrip(myblockchain_path)     
  my_lib = myblockchain_path + "/lib/"
  my_inc = myblockchain_path + "/include/"

  if os.path.isdir(my_lib + "/myblockchain"):
    my_lib = my_lib + "/myblockchain"
 
  if os.path.isdir(my_inc + "myblockchain/storage"):
    my_inc = my_inc + "myblockchain/"
  
  ndb_inc = my_inc + "/storage/ndb"
 
  conf.env.my_lib = my_lib
  conf.env.my_inc = my_inc
  conf.env.ndb_inc = ndb_inc
    
  conf.check_tool('compiler_cxx')
  conf.check_tool('node_addon')

  conf.recurse("Adapter/impl/")

def build(ctx):
  ctx.recurse("Adapter/impl/")

