# Copyright (c) 2015, Oracle and/or its affiliates. All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA

# binaries
usr/bin/myblockchain_client_test
usr/bin/myblockchain_client_test_embedded
usr/bin/myblockchaintest
usr/bin/myblockchaintest_embedded
# manpages
usr/share/man/man1/myblockchain_client_test.1
usr/share/man/man1/myblockchain_client_test_embedded.1
usr/share/man/man1/myblockchain-test-run.pl.1
usr/share/man/man1/myblockchaintest.1
usr/share/man/man1/myblockchaintest_embedded.1
# plugins
usr/lib/myblockchain/plugin/auth.so
usr/lib/myblockchain/plugin/auth_test_plugin.so
usr/lib/myblockchain/plugin/daemon_example.ini
usr/lib/myblockchain/plugin/ha_example.so
usr/lib/myblockchain/plugin/libdaemon_example.so
usr/lib/myblockchain/plugin/libtest_framework.so
usr/lib/myblockchain/plugin/libtest_services.so
usr/lib/myblockchain/plugin/libtest_services_threaded.so
usr/lib/myblockchain/plugin/qa_auth_client.so
usr/lib/myblockchain/plugin/qa_auth_interface.so
usr/lib/myblockchain/plugin/qa_auth_server.so
usr/lib/myblockchain/plugin/replication_observers_example_plugin.so
usr/lib/myblockchain/plugin/rewrite_example.so
usr/lib/myblockchain/plugin/debug/auth.so
usr/lib/myblockchain/plugin/debug/auth_test_plugin.so
usr/lib/myblockchain/plugin/debug/daemon_example.ini
usr/lib/myblockchain/plugin/debug/ha_example.so
usr/lib/myblockchain/plugin/debug/libdaemon_example.so
usr/lib/myblockchain/plugin/debug/libtest_framework.so
usr/lib/myblockchain/plugin/debug/libtest_services.so
usr/lib/myblockchain/plugin/debug/libtest_services_threaded.so
usr/lib/myblockchain/plugin/debug/qa_auth_client.so
usr/lib/myblockchain/plugin/debug/qa_auth_interface.so
usr/lib/myblockchain/plugin/debug/qa_auth_server.so
usr/lib/myblockchain/plugin/debug/replication_observers_example_plugin.so
usr/lib/myblockchain/plugin/debug/rewrite_example.so
# test suite
usr/lib/myblockchain-test/*
# legal
usr/share/doc/myblockchain-community-test/COPYING
usr/share/doc/myblockchain-community-test/README
